# micromamba env create -f environment.yml
name: projekat
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pip
  - scikit-image
  - scipy
  - pytorch
  - torchvision
  - albumentations
  - scikit-learn
  - pip:
      # conda-forge build simsimd (albucore zavisnost) je na arm64 prazan paket
      # (0 fajlova) -> instaliramo ga preko pip-a da albumentations radi
      - simsimd
